/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Structure Access
 #	author : miyako
 #	2017/03/05
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Structure Access

		case 1 :
			CREATE_ELEMENTS_FROM_XML(pResult, pParams);
			break;

	}
}

// ------------------------------- Structure Access -------------------------------


void CREATE_ELEMENTS_FROM_XML(sLONG_PTR *pResult, PackagePtr pParams)
{
	PA_CreateElementsFromXMLDefinition((PA_Unistring *)(pParams[0]));
}

