/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Structure Access
 #	author : miyako
 #	2017/03/05
 #
 # --------------------------------------------------------------------------------*/



// --- Structure Access
void CREATE_ELEMENTS_FROM_XML(sLONG_PTR *pResult, PackagePtr pParams);
